### ISSUE TITLE
ERROR: unable to launch VLC

### ISSUE THREAD

**Issue by LDighera** [ravn/silicondust-hdhomerun#1]
OS: 
Linux debian-lenovo 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

Issue: 
When clicking the 'View' button to the right of the channel, I receive the 'ERROR: unable to launch VLC' error message.
I get this error whether VLC is running or not at the time I click the 'View' button.
I compiled hdhomerun_config_gui prior to installing VLC. 

When launching VLC, I receive this error:
     /home/larry (pts3) $ hdhomerun_config_gui
    Gtk-Message: 09:53:20.362: Failed to load module "appmenu-gtk-module"

apt output: appmenu-gtk-module-common is already the newest version (0.7.6-2).

What am I doing wrong?

**Comment by LDighera** [comment]
I found running hdhomerun_config_gui as root overcame the issue.

Now, I'm trying to figure out how to add hdhomerun_config_gui to the KDE Plasma Application Launcher.

**Comment by ravn** [comment]
This is not support or open source software. I'm just collecting the binary blobs for historic purposes.
